#!/usr/bin/env bash
# Writes apps/ios/Config/Dev.xcconfig (gitignored) from a web .env.local, without printing the key.
# Usage: apps/ios/scripts/make-dev-xcconfig.sh /path/to/.env.local
set -euo pipefail
ENV_FILE="${1:?usage: make-dev-xcconfig.sh /path/to/.env.local}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/Config/Dev.xcconfig"
key="$(grep -E '^VITE_CLERK_PUBLISHABLE_KEY=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"'"'"' \r')"
url="$(grep -E '^VITE_CONVEX_URL=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"'"'"' \r')"
[ -n "$key" ] || { echo "VITE_CLERK_PUBLISHABLE_KEY not found in $ENV_FILE" >&2; exit 1; }
url="${url:-https://decisive-iguana-954.convex.cloud}"
{
  echo "// Generated by scripts/make-dev-xcconfig.sh. Gitignored: never commit."
  echo "CONVEX_URL = ${url/:\/\//:/\$()/}"
  echo "CLERK_PUBLISHABLE_KEY = $key"
} > "$OUT"
echo "wrote apps/ios/Config/Dev.xcconfig (key ${key%%_*}_…, $( [[ $key == pk_test_* ]] && echo development || echo production ) instance)"
